### ISSUE TITLE
Publish on Hex.pm

### ISSUE THREAD

**Issue by vassilevsky** [palkan/influx_udp#11]
Using dependencies from Hex.pm is so much better :)

**Comment by palkan** [comment]
> Using dependencies from Hex.pm is so much better :)

Absolutely!

I think the reason why it hasn't been published is that some of the deps were not on hex.pm at the last time I touched this lib.

I should check again

**Comment by palkan** [comment]
Finally!

https://github.com/palkan/influx_udp/releases/tag/v1.0.0
