### ISSUE TITLE
The mistake in using inet:parse_address/1 function

### ISSUE THREAD

**Issue by Howld** [palkan/influx_udp#9]
Link1: https://github.com/palkan/influx_udp/blob/master/src/influx_udp.erl#L170
Link2: https://github.com/palkan/influx_udp/blob/master/src/influx_udp.erl#L226

Issue:
The parameter 'host' is a atom type in Link1, but inet:parse_address/1 needs a string type in Link2.

**Comment by palkan** [comment]
Good catch! Thanks!

Would you like to propose a PR?

**Comment by palkan** [comment]
Closed by #10
